# Generated by Django 5.0.3 on 2024-03-08 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('instagram', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_likes',
            field=models.IntegerField(default=0),
        ),
    ]
